### ISSUE TITLE
[DMP 2024]: Open Banking/PISP Fintech App Framework Version 3.0

### ISSUE THREAD

**Issue by DavidH-1** [openMF/pisp-app#5]
## Description
Across our ecosystem we're seeing more and more adoption and innovation from fintechs. A huge democratizing force across the financial services sector is the Open Banking movement providing Open Banking APIs to enable third parties to directly interact with customers of financial institutions. We have recently started providing an Open Banking API layer that will allow financial institutions using Mifos and Fineract to offer third parties access to requesting account information and initiating payments via these APIs. Most recently the Mojaloop community, led by Google, has led the development of a centralized PISP API for 3PPI (3 Party Payment Initiation)
To demonstrate these Open Banking APIs and use cases that third parties and fintechs can provide we have developed a cross-platform reference mobile app on Kotlin to showcase a number of these features. It currently connects with the mock data layer - this project would extend upon that app framework to consume Mojaloop 3PPI/PISP APIs.
This app showcases the financial services that can be made possible when an individual has access to digital financial services through digital public infrastructure provide by Mifos DPGs. The breadth and variety of apps that could be built leveraging these APIs from region to region is endless. We would like this app to be built in an extensible and modular fashion such that core libraries and components could be re-used across different use cases with this framework as the foundation and multiple reference apps on top. Applications include personal financial management apps aggregating information from multiple bank accounts in one place, wallet apps allowing payments to be made from different banks, lending apps, leveraging data and insight from multiple accounts, savings apps, etc.
Roadmap: 
UI Design: Following the [Google Whitepaper](https://static.googleusercontent.com/media/nextbillionusers.google/en//tools/3PPI-2021-whitepaper.pdf), I created [Figma Mocups](https://www.figma.com/proto/ZkQJHzXWfjZugpTtz1MFdt/Mifos-PISP-App?node-id=10-27&starting-point-node-id=101:32&scaling=scale-down&mode=design&t=vtBsVklbforA4MiB-1) prototype to develop UI screens and components for both Android and iOS platforms.
Backend Development: Based on available resources, the immediate priority is to create a robust backend system capable of seamlessly consuming Mojaloop 3PPI SDK endpoints.
Transitioning to Real-Time Data: We will replace the temporary mock data layer with a production-ready API and refactor any shortcomings to ensure real-time data interaction.
Documentation: Documentation will include reference guides for the 3PPI API specifically for PISP participants as well as diagrams illustrating the system architecture.

## Goals
- [1] [Define user stories and scope of work on mobile app vs back-end integration with Mojaloop via PH-EE ]
- [2] [Implement UI design mockups from 2023 ]
- [3] [Implement consent flows via Mojaloop 3PPI APIs ]
- [4] Develop back-end integration with PH-EE to consume Mojaloop 3PPI SDK endpoints.]
- [5] [Transition to real-time data: replace mock data later with production-ready API
- [6] [Project Documentation 

### Expected Outcome

Intern would work on refining the initial architecture of the framework, the UI and user experience, core use cases including customer authentication and onboarding that was implemented in 2020 and integrating with the Fineract Open Banking APIs and Mojaloop PISP APIs to demonstrate use cases around account information request and payment initiation. 

Adding PISP capability to Mifos mobile applications helps to advance DPI as it’s a powerful way to demonstrate other transaction flow and financial services that can be unlocked once an underbanked individual is equipped with a digital wallet powered by Mifos. This would be a continuation of the project worked on in 2023 where Lakhwinder Singh implemented the following:
Project reshaping with where a new Kotlin architecture for the PISP app defined
Deployment of Mojaloop with third party support and ensuant testing of this with Mojaloop Testing Toolkit and deployment of Mojaloop Third Party SDK adapter
Implementation of mock data layer
Development of UI mockups via Figma. 

Our desired outcome is to have a  stand-alone reference third party fintech app that demonstrates 3rd party initiation/ Open Banking APIs or in this case Mojaloop PISP APIs. The app itself would need its own separate user management, etc but then it would pull in data by authorizing consent via the Mojaloop 3PPI/PISP API to pull in transactional data from a mifos/fineract account and most importantly we’d want to use this reference fintech app to demonstrate the use of Mojaloop/Google 3PPI PISP APIs whereby a user could authorize and establish consent across any bank participating in a mojaloop switch to the fintech to initiate transactions through mojaloop via their accounts managed in Mifos/Fineract
Aggregating account information across multiple banks/financial institution
Initiating payments across multiple financial institutions
Integrate with additional Fineract Open Banking APIs
Integrate with Mojaloop PISP APIs. 
Leverage completed components of UI library

### Implementation Details

Source code: https://github.com/openMF/pisp-app
Figma Design Mockups: https://www.figma.com/proto/ZkQJHzXWfjZugpTtz1MFdt/Mifos-PISP-App?node-id=10-27&starting-point-node-id=101%3A32&scaling=scale-down&t=vtBsVklbforA4MiB-1
Previous Development:
2023 Mifos Summer of Code Final Report - https://gist.github.com/lssarao/fc1293ad3c36d51317358348323b80c0
2020 Google Summer of Code Final Report - https://gist.github.com/ankurs287/4ef7c3de462073bf36bd5247479cb176
Google Whitepaper on 3PPI: https://static.googleusercontent.com/media/nextbillionusers.google/en//tools/3PPI-2021-whitepaper.pdf
UK Open Banking API Standard: https://standards.openbanking.org.uk/
Open Banking Developer Zone: https://openbanking.atlassian.net/wiki/spaces/DZ/overview
Examples of Open Banking Apps: https://www.ft.com/content/a5f0af78-133e-11e9-a581-4ff78404524e

### Product Name

Open Banking/PISP Fintech App Framework 

### Organisation Name

The Mifos Initiative

### Domain

Financial Inclusion

### Tech Skills Needed

Java, JavaScript, RESTful APIs, Spring Boot, Other

### Mentor(s)

[@edcable](https://github.com/edcable)

### Category

Backend, Mobile

**Comment by AbhimanyuSamagra** [comment]
Do not ask process related questions about how to apply and who to contact in the above ticket. The only questions allowed are about technical aspects of the project itself. If you want help with the process, you can refer instructions listed on [Unstop](https://unstop.com/competitions/dedicated-mentoring-program-dmp-2024-code-for-govtech-932803?lb=7gWXVfKv) and any further queries can be taken up on our [Discord channel](https://discord.com/invite/VPrXf7Jxpr) titled DMP queries. Here's a [Video Tutorial](https://youtu.be/nMW-nD8WzHY) on how to submit a proposal for a project.

**Comment by renuka010** [comment]
Hi @DavidH-1, I would like to work on this project. I am familiar with Java, RestApis and Spring framework.

**Comment by DavidH-1** [comment]
Hi @renuka010 that is great.  Please see the comment above from @AbhimanyuSamagra on how to apply.  Do you have any technical questions you need support on?  We have also setup a channel in Mifos Slack to answer technical questions #C4GT-mojafos-2024 where we have answered several questions already that may help you.

**Comment by AieshaShetty** [comment]
Hi, @DavidH-1 , I would love to contribute to this project. My tech stack includes Java, Spring Boot, Jpa. I also have some issues in setting up and would need a couple of days to figure out and I'll be reaching out to you soon in Mifos Slack for further tech-related doubts. I have also been a mentee at C4GT'23 and I have integrated java-jwt for enhancing security and authorization.

**Comment by karimjindani** [comment]
##Week 1
-[ ] Read the documentation of the pisp-app and mojaloop. 
-[ ] Go through the linking process and transaction diagrams on the GitHub repository.
-[ ] Scope out what is to be designed/developed.
-[ ] Start by cloning the mojafos repository and try to execute the project.

##Week 2
-[ ] Setup this environment ( Mini-loop+ Third party sdk) 
-[ ] Go through the linking flows
-[ ] Read and understand from the links provided, of third-party api and miniloop
-[ ] Go through Webauthn.io and webauthn.guide
-[ ] Setup a virtual machine on laptop, mount Ubuntu on it for miniloop setup.

##Week 3
-[ ] Sequence Diagram on Plantuml including registration, linking, and transfer/payment.
-[ ] User Interface for Register Flow on draw.io
-[ ] Create a Hello World Android App

**Comment by karimjindani** [comment]
# Weekly Goals
## Week 1
- [ ] Read the documentation of the pisp-app and mojaloop.
- [ ] Go through the linking process and transaction diagrams on the GitHub repository.
- [ ] Scope out what is to be designed/developed.
- [ ] Start by cloning the mojafos repository and try to execute the project.

## Week 2
- [ ] Setup this environment ( Mini-loop+ Third party sdk)
- [ ] Go through Linking Flows sequence diagrams
- [ ] Read and understand from the links provided, of third-party api and miniloop
- [ ] Go through Webauthn.io and webauthn.guide
- [ ] Setup a virtual machine on laptop, mount Ubuntu on it for miniloop setup.

## Week 3
- [ ] Sequence Diagram on Plantuml
	- [ ] App Registration Flow
	- [ ] Account Linking Flow
	- [ ] Payment/Transfer Flow
- [ ] Create a Hello World Android App 
- [ ] Create User Interface for PISP App on Draw.io
	- [ ] App Regisration User Screens
	- [ ] Account Linking User Screens
	- [ ] Payment Transfer User Screens

**Comment by PalakMishra-eq** [comment]
# Task Completion Update

## Week 1
- [ ] Read the documentation
- [ ] Read and understood the linking process
- [ ] Cloned the Repo on my local system

## Week 2
- [ ] Read and completed tasks
- [ ] Setup oracle VM 6 gb, mounted ubuntu and completed installation.

## Week 3
- [ ] @startuml
actor "User" as channel
participant "PISP APP" as sdk
participant "Email" as mojaloop
participant "App Service" as serv
channel -> sdk: Click Register
sdk --> channel: Show registeration screen
channel -> sdk: Enter name and email, click Submit
sdk -> serv: Registeration request
serv -> serv: Check existing user\nGenerate OTP\nSend OTP
serv -> mojaloop: OTP sent
sdk --> channel: Ask OTP
channel --> mojaloop: Retrieve OTP
channel -> sdk : Enter OTP
sdk -> serv: Verify OTP
serv -> serv: OTP Verified\nAccount Created
sdk -> channel: Registration Successful
@enduml


- [ ] @startuml
actor "User" as channel
participant "PISP APP" as app
participant "App Service" as serv
participant "Bank" as bnk
channel -> app: Click Login
app --> channel: Show login screen
channel -> app: Enter eamil and password,\nclick Login
app -> serv: Login request
serv -> serv: Check existing user\nverify email\nverify password
serv --> app: Login Validated
app -> channel: Home Page
app --> channel: Select Bank\nDropdown List
channel -> app: Bank Selected\nIFSC code entered\nAccount Number entered\nUser Name entered
app --> serv: Banking Details Passed \non for Bank verification
serv-> bnk:Request verification \nfor user details.\nRequest Linking
bnk-> bnk: User Verification
bnk --> channel: OTP sent for linking process
bnk-> serv: One time password sent\nfor linking process
serv-->app: Request OTP for \nlinking account
app -> channel: Request OTP
channel -> app: OTP Sent
app-->serv: OTP Sent
serv -> bnk: OTP Sent for verification
bnk->bnk: Verify OTP
bnk -> serv: OTP verified\nConnection established
serv-> app: Bank account linked.
app-> channel: Bank account linked\nfor transaction
@enduml

**Comment by PalakMishra-eq** [comment]
![image](https://github.com/user-attachments/assets/ce2e5ba1-a896-4746-ab99-ffd9af08197c)

**Comment by PalakMishra-eq** [comment]
![image](https://github.com/user-attachments/assets/56ec4439-e6f8-4589-8152-d5242cc559fc)
![image](https://github.com/user-attachments/assets/0075a3ba-d1b3-45ec-9c12-fcfd48f28f7e)

**Comment by PalakMishra-eq** [comment]
https://drive.google.com/file/d/1H7cpG94oRSj3zOhRsu6Gx-9w3kIkieJK/view?usp=sharing

**Comment by PalakMishra-eq** [comment]
[https://github.com/PalakMishra-eq/SudoMifos/branches](url)

**Comment by Jadhav-Dhanashri** [comment]
Hello mentainers,
I'm Dhanashri Jadhav, a GSOC aspirant.
Eager to contribute to GSoC projects & actively participate.
Looking forward to collaborating & learing from all of you.
Thank you!
